######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 17 01:38:18 2011
######################################################################

QT       += core network qt3support xml
CONFIG += qtestlib
TEMPLATE = app
CONFIG += moc
INCLUDEPATH += . \
    ../trunk/include

# Input
SOURCES += GRIProcList_Test.cpp
