HEADERS += GRIProcess.h\
#GRIAnalysisThread.h\
GRIBuffer.h\
#GRICLI.h\
#GRICalibrate.h\
#GRICalibration.h\
#GRIClientSocket.h\
#GRICommandAndControl.h\
#GRIDAQ.h\
GRIDAQThread.h\
GRIDataBlock.h\
GRIDefines.h\
#GRIHistDraw.h\
#GRIHistogrammer.h\
GRILoader.h\
GRIMath.h\
GRIMemoryManager.h\
#GRIParamList.h\
#GRIAnalysis.h\
GRIProcessObj.h\
GRIProcessThread.h\
GRIRegulator.h\
#GRIRunManager.h\
#GRIServer.h\
#GRIServerThread.h\
#GRIXMLParser.h
