SOURCES += GRIProcessThread.cpp\
GRIAnalysisThread.cpp\
GRIBuffer.cpp\
GRICLI.cpp\
#GRICalibrate.cpp\
#GRICalibration.cpp\
GRIClientSocket.cpp\
GRICommandAndControl.cpp\
GRIDAQThread.cpp\
GRIDataBlock.cpp\
GRIDiagnostics.cpp\
GRIHistDraw.cpp\
GRIHistogrammer.cpp\
GRILoader.cpp\
GRILogger.cpp\
GRIMath.cpp\
GRIMemoryManager.cpp\
GRIMenuStructure.cpp\
GRIRegulator.cpp\
GRIRunManager.cpp\
GRIServer.cpp\
GRIServerThread.cpp\
GRIXMLParser.cpp\
GRILogMessage.cpp\
GRIUserLoader.cpp\
GRIObject.cpp\
