SOURCES += GRIProcessThread.cpp\
#GRIAnalysisThread.cpp\
GRIBuffer.cpp\
#GRICLI.cpp\
#GRICalibrate.cpp\
#GRICalibration.cpp\
#GRIClientSocket.cpp\
#GRICommandAndControl.cpp\
GRIDAQThread.cpp\
GRIDataBlock.cpp\
#GRIHistDraw.cpp\
#GRIHistogrammer.cpp\
GRILoader.cpp\
GRIMath.cpp\
GRIMemoryManager.cpp\
#GRIAnalysis.cpp\
GRIRegulator.cpp\
#GRIRunManager.cpp\
#GRIServer.cpp\
#GRIServerThread.cpp\
#GRIXMLParser.cpp\
#main.cpp
