######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 17 01:38:18 2011
######################################################################

QT       += core network qt3support xml
CONFIG += qtestlib
TEMPLATE = app
CONFIG += moc
DEPENDPATH += .
DEPENDPATH +=    ../framework/include
DEPENDPATH +=    ../framework/source

INCLUDEPATH += . \
    ../framework/include \
    ../framework/source \
    ../tests/QtTestUtil

#root headers
ROOTDIR = /home/ben/Downloads/root
INCLUDEPATH += $$ROOTDIR/include

ROOTSYSLIB += $$ROOTDIR/lib
INCLUDEPATH += $$ROOTSYSLIB
LIBS += $$ROOTSYSLIB/libCint.so
LIBS += $$ROOTSYSLIB/libMatrix.so
LIBS += $$ROOTSYSLIB/libMathCore.so
LIBS += -L/$$ROOTSYSLIB
LIBS += -L$$ROOTSYS/lib -lCore -lHist
# Input

include(../framework/include/finclude.pri)
include(../framework/source/fsource.pri)

SOURCES += main.cpp \
    GRILogger_Test.cpp \
    GRIProcList_Test.cpp



GRIFDIR=/home/ben/Documents/grif
GRIFPROJECTDIR=$$GRIFDIR/examples/simulator

# External libraries
INCLUDEPATH += $$GRIFDIR/external

DEFINES += GRIFPROJECTDIR=\"\\\"/home/ben/Documents/grif\\\"\"
#DEFINES += projDir_aux(projDir)='$${LITERAL_HASH}projDir'
#DEFINES += projDir=projDir_aux(GRIFPROJECTDIR)
